# Site settings
title: Code tips
email: frozon@gmail.com
github: "https://github.com/frozon"
baseurl: ""
url: "http://frozon.github.io"

author:
  name: Thomas Lauro
  email: frozon@gmail.com
  github: frozon
  twitter: pkiwy
  bio: Maybe not so technical blog for sharing some code tips

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

# Build settings
markdown: kramdown
permalink: pretty

paginate: 10
paginate_path: "page:num"
highlighter: pygments